services:
  web:
    image: ghcr.io/ahmed-azhari93/docker-practice:7e69891ede858f5f7a6846d983a155e25767c1f3
    ports:
      - "8082:80"

  backend:
    image: python:3.13-alpine
    command: python -m http.server 8000
